#!/bin/bash

SCPTARGET=root@lvme4j1ze1nu2gs.delivery.puppetlabs.net
scp /Users/puppet/Repos/enterprise_tasks/plans/ha_puppetdb_sync.pp ${SCPTARGET}:/opt/puppetlabs/installer/share/boltdir/site/enterprise_tasks/plans/ha_puppetdb_sync.pp
