#!/bin/bash

SCPTARGET=root@$1
scp -r /Users/puppet/Repos/enterprise_tasks/plans ${SCPTARGET}:/opt/puppetlabs/installer/share/boltdir/site/enterprise_tasks/plans
scp -r /Users/puppet/Repos/enterprise_tasks/tasks ${SCPTARGET}:/opt/puppetlabs/installer/share/boltdir/site/enterprise_tasks/tasks
