#!/bin/bash
#make sure you are mfa logged in before you run this

aws sts assume-role --role-arn  arn:aws:iam::180094860577:role/Marketplace-Developer --role-session-name "marketplace-assumed-role" --profile marketplace > assume-role.out
id=$(cat assume-role.out | jq '.Credentials.AccessKeyId')
secret=$(cat assume-role.out | jq '.Credentials.SecretAccessKey')
token=$(cat assume-role.out | jq '.Credentials.SessionToken')
export AWS_ACCESS_KEY_ID=${id}
export AWS_SESSION_TOKEN=${token}
export AWS_SECRET_ACCESS_KEY=${secret}