#!/bin/bash
#grabs a work repo and configures the remote settings
REPO=$1
cd /Users/puppet/Repos
git clone git@github.com:puppetlabs/${REPO}.git
cd ${REPO}
git remote set-url origin  git@github.com:actowery/${REPO}.git
git remote add upstream git@github.com:puppetlabs/${REPO}.git
git remote set-url --push upstream no_push
echo 'New repo successfully created. URLs set and push to upstream disabled'
